version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - 9000:9000
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - ./:/go/src
    working_dir: /go/src
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://mysql:3306
    command: "sh -c \"dbmate migrate && air\""

  mysql:
    image: mysql:5.7
    platform: linux/x86_84
    environment:
      MYSQL_DATABASE: go_mvc_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/db
    ports:
      - 3306:3306

